// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaF_9Zhi6j0DAFOnIkrdWffkORKfyZlY',
    appId: '1:861082610567:web:40e381e55b4a81e16c4122',
    messagingSenderId: '861082610567',
    projectId: 'lab-app-916b8',
    authDomain: 'lab-app-916b8.firebaseapp.com',
    storageBucket: 'lab-app-916b8.appspot.com',
    measurementId: 'G-L6LEM7MWG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnHkmHc183O-hF8_6Up7bs12UMtc0plw',
    appId: '1:861082610567:android:bc0a3aa6f6f97f2e6c4122',
    messagingSenderId: '861082610567',
    projectId: 'lab-app-916b8',
    storageBucket: 'lab-app-916b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvcLM8ITOlSdvKiUm4Msx9y5ouVXGHv8',
    appId: '1:861082610567:ios:5c825f02dfaab6846c4122',
    messagingSenderId: '861082610567',
    projectId: 'lab-app-916b8',
    storageBucket: 'lab-app-916b8.appspot.com',
    iosClientId:
        '861082610567-l3lki1v4c4ui8cm96sor70t6kc638mr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSerch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvcLM8ITOlSdvKiUm4Msx9y5ouVXGHv8',
    appId: '1:861082610567:ios:5c825f02dfaab6846c4122',
    messagingSenderId: '861082610567',
    projectId: 'lab-app-916b8',
    storageBucket: 'lab-app-916b8.appspot.com',
    iosClientId:
        '861082610567-l3lki1v4c4ui8cm96sor70t6kc638mr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSerch',
  );
}
